version: '3'

services:
  mysql-01:
    image: mysql:8.0
    container_name: mysql-01
    restart: always
    environment:
      MYSQL_DATABASE: IMDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: guilherme
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-01:/var/lib/mysql